In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('E:\data mining\dataset_csv\dataset_imp_date_time.csv')

In [3]:
data=data.iloc[:,2:]

In [4]:
data

,Vehicle_ID,Sample_ID,State_Of_Health_Battery,Battery_Generation,Fleet_ID,Country,Vehicle_MRK_TYPE,CURRENT_YEARLY_MILEAGE,Mounted_Battery_Generation,Measure_R_D,Engine_Type,Geo_Area,City,Cluster,IS_PATTERN_AVAILABLE,IS_FLEET_TOF_MONITORED,IS_CHECKED_IN_VDA,Battery_Supplier,Battery_Replacement_date1,send_time1
0,1.0,262526303.0,67.500,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,2015-08-01 00:00:00,2019-03-11 17:35:14
1,1.0,115517796.0,72.000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,2015-08-01 00:00:00,2017-11-10 18:09:35
2,1.0,251857645.0,54.250,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,2015-08-01 00:00:00,2019-02-21 07:24:22
3,1.0,47893312.0,95.500,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,2015-08-01 00:00:00,2015-12-20 16:26:27
4,1.0,96601019.0,76.250,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,2015-08-01 00:00:00,2017-06-12 13:01:16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853462,3005.0,91318742.0,91.992,5.0,283.0,17.0,7.0,32.0,5.0,42.0,2.0,1.0,111.0,5.0,0.0,0.0,1.0,3.0,2013-02-01 00:00:00,2017-04-04 12:02:45
853463,3005.0,34240175.0,97.000,5.0,283.0,17.0,7.0,32.0,5.0,42.0,2.0,1.0,111.0,5.0,0.0,0.0,1.0,3.0,2013-02-01 00:00:00,2012-12-19 10:35:28
853464,3005.0,8913813.0,100.000,5.0,283.0,17.0,7.0,32.0,5.0,42.0,2.0,1.0,111.0,5.0,0.0,0.0,1.0,3.0,2013-02-01 00:00:00,2015-11-16 13:39:16
853465,3005.0,62422559.0,95.117,5.0,283.0,17.0,7.0,32.0,5.0,42.0,2.0,1.0,111.0,5.0,0.0,0.0,1.0,3.0,2013-02-01 00:00:00,2016-09-07 11:13:26
853466,3005.0,56762577.0,95.117,5.0,283.0,17.0,7.0,32.0,5.0,42.0,2.0,1.0,111.0,5.0,0.0,0.0,1.0,3.0,2013-02-01 00:00:00,2017-04-12 11:48:48

In [5]:
import numpy as np

In [6]:
data['send_time1']=pd.to_datetime(data['send_time1']).values.astype(np.int64) // 10 ** 6

In [7]:
data['Battery_Replacement_date1']=pd.to_datetime(data['Battery_Replacement_date1']).values.astype(np.int64) // 10 ** 6

In [8]:
data=data.drop(['Vehicle_ID','Sample_ID'],axis=1)

In [9]:
from sklearn.cluster import DBSCAN

In [21]:
clustering=DBSCAN(eps=0.3,min_samples=40)

In [22]:
clustering.fit(data)

DBSCAN(eps=0.3, min_samples=40)

In [23]:
labels=clustering.labels_

In [24]:
len(set(labels)) - (1 if -1 in labels else 0)

10